server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true